-- Seed equipment data
-- Headgear (20 items)
INSERT INTO public.equipment (name, category, tier, stat_modifiers, unlock_level, description) VALUES
('Traveler''s Hood', 'headgear', 1, '{"defense": 2}', 1, 'A simple hood for travelers'),
('Iron Helm', 'headgear', 1, '{"defense": 5}', 3, 'Basic iron protection'),
('Bandit Mask', 'headgear', 1, '{"agility": 3}', 2, 'Conceals identity'),
('Mage''s Circlet', 'headgear', 2, '{"magic_power": 8}', 5, 'Enhances magical abilities'),
('Bone Crown', 'headgear', 2, '{"dark_magic": 10}', 7, 'Made from ancient bones'),
('Hunter''s Cap', 'headgear', 1, '{"perception": 5}', 4, 'Helps spot prey'),
('Steel Visor', 'headgear', 2, '{"defense": 12}', 8, 'Heavy steel protection'),
('Warlock''s Hood', 'headgear', 3, '{"magic_power": 15, "dark_magic": 5}', 12, 'Infused with dark energy'),
('Crystal Helm', 'headgear', 3, '{"magic_power": 12, "defense": 8}', 10, 'Crystalline protection'),
('Serpent Coiled Headband', 'headgear', 2, '{"poison_resist": 10}', 6, 'Protects against venom'),
('Helm of Echoes', 'headgear', 3, '{"tactical_bonus": 15}', 14, 'Whispers tactical advice'),
('Frosthelm Cap', 'headgear', 2, '{"cold_resist": 15}', 9, 'Resists freezing temperatures'),
('Ashen Hood', 'headgear', 2, '{"stealth": 10}', 7, 'Camouflages in desert'),
('Dragonbone Mask', 'headgear', 4, '{"defense": 20, "fire_resist": 10}', 16, 'Carved from dragon skull'),
('Silver Crown of Light', 'headgear', 4, '{"light_magic": 20}', 18, 'Radiates holy energy'),
('Stormbreaker Helm', 'headgear', 4, '{"lightning_resist": 20}', 17, 'Channels storm power'),
('Whisperveil', 'headgear', 3, '{"invisibility_chance": 5}', 13, 'Grants chance to vanish'),
('Helm of Drowned Kings', 'headgear', 4, '{"water_magic": 18}', 19, 'Recovered from ocean depths'),
('Wolf''s Pelt Headdress', 'headgear', 2, '{"strength": 8}', 6, 'Grants wolf-like ferocity'),
('Mask of Forgotten Faces', 'headgear', 5, '{"all_stats": 10}', 20, 'Changes appearance at will');

-- Armor (20 items)
INSERT INTO public.equipment (name, category, tier, stat_modifiers, unlock_level, description) VALUES
('Leather Tunic', 'armor', 1, '{"defense": 5}', 1, 'Basic leather protection'),
('Chainmail Vest', 'armor', 1, '{"defense": 10}', 3, 'Interlocking metal rings'),
('Mage''s Robe', 'armor', 2, '{"magic_power": 12}', 5, 'Enchanted fabric'),
('Bone Plated Armor', 'armor', 2, '{"defense": 15, "dark_resist": 5}', 7, 'Reinforced with bones'),
('Scaled Hide Armor', 'armor', 2, '{"defense": 18}', 8, 'Dragon scale protection'),
('Guardian Plate', 'armor', 3, '{"defense": 25}', 10, 'Heavy plate armor'),
('Warlock''s Mantle', 'armor', 3, '{"magic_power": 20, "dark_magic": 10}', 12, 'Dark energy infused'),
('Frostforged Mail', 'armor', 3, '{"defense": 22, "cold_resist": 15}', 11, 'Forged in ice'),
('Sandsteel Armor', 'armor', 2, '{"defense": 16, "heat_resist": 10}', 9, 'Desert-forged metal'),
('Obsidian Carapace', 'armor', 4, '{"defense": 30, "fire_resist": 20}', 15, 'Volcanic glass armor'),
('Cloak of Shadows', 'armor', 3, '{"stealth": 20, "agility": 10}', 13, 'Blends with darkness'),
('Crystalweave Armor', 'armor', 3, '{"magic_power": 18, "defense": 15}', 12, 'Woven with mana crystals'),
('Sunforged Chestplate', 'armor', 4, '{"defense": 28, "light_magic": 15}', 16, 'Blessed by sun priests'),
('Bloodstained Battlegarb', 'armor', 3, '{"strength": 15, "defense": 20}', 14, 'Worn by legendary warrior'),
('Echo Mantle', 'armor', 4, '{"skill_amplification": 25}', 17, 'Resonates with skills'),
('Spectral Armor', 'armor', 4, '{"defense": 20, "evasion": 20}', 18, 'Partially incorporeal'),
('Wyrmhide Vest', 'armor', 3, '{"defense": 24, "all_resist": 10}', 13, 'Lesser dragon hide'),
('Seafoam Scale Armor', 'armor', 3, '{"defense": 22, "water_magic": 12}', 14, 'From sea serpent'),
('Emberheart Armor', 'armor', 4, '{"defense": 26, "fire_magic": 18}', 19, 'Contains living flame'),
('Deathknight''s Cuirass', 'armor', 5, '{"defense": 35, "dark_magic": 25}', 20, 'Cursed armor of fallen knight');

-- Gauntlets (20 items)
INSERT INTO public.equipment (name, category, tier, stat_modifiers, unlock_level, description) VALUES
('Leather Gloves', 'gauntlets', 1, '{"dexterity": 3}', 1, 'Simple leather gloves'),
('Iron Gauntlets', 'gauntlets', 1, '{"strength": 5}', 3, 'Heavy iron fists'),
('Mage''s Gloves', 'gauntlets', 2, '{"magic_power": 8}', 5, 'Enhances spellcasting'),
('Boneclaw Gauntlets', 'gauntlets', 2, '{"damage": 10}', 7, 'Sharpened bone claws'),
('Venomtouch Gloves', 'gauntlets', 2, '{"poison_damage": 12}', 6, 'Coated in toxins'),
('Frostbite Gauntlets', 'gauntlets', 2, '{"ice_damage": 10}', 8, 'Freezes on contact'),
('Sandfist Gloves', 'gauntlets', 2, '{"earth_magic": 8}', 7, 'Controls sand'),
('Shadow Weave Gloves', 'gauntlets', 3, '{"dark_magic": 15}', 11, 'Woven from shadows'),
('Flameforged Gauntlets', 'gauntlets', 3, '{"fire_damage": 15}', 10, 'Burns enemies'),
('Crystal Clasp', 'gauntlets', 3, '{"magic_power": 12, "damage": 8}', 12, 'Crystal-enhanced grip'),
('Echo Strike Gloves', 'gauntlets', 3, '{"damage": 18}', 13, 'Strikes echo twice'),
('Serpentcoil Gauntlets', 'gauntlets', 3, '{"poison_damage": 15, "agility": 8}', 12, 'Serpent-wrapped'),
('Stormgrip Gauntlets', 'gauntlets', 4, '{"lightning_damage": 20}', 15, 'Channels lightning'),
('Dragonbone Gauntlets', 'gauntlets', 4, '{"damage": 22, "fire_resist": 10}', 16, 'Dragon bone claws'),
('Emberfist Wraps', 'gauntlets', 3, '{"fire_damage": 18}', 14, 'Wrapped in embers'),
('Ironthorn Gauntlets', 'gauntlets', 3, '{"damage": 16, "defense": 8}', 13, 'Thorned metal'),
('Runic Gloves', 'gauntlets', 4, '{"all_magic": 15}', 17, 'Inscribed with runes'),
('Drowned Grip', 'gauntlets', 4, '{"water_magic": 18, "damage": 12}', 18, 'From ocean depths'),
('Gilded Talons', 'gauntlets', 4, '{"damage": 20, "light_magic": 10}', 19, 'Golden claws'),
('Voidtouch Gauntlets', 'gauntlets', 5, '{"damage": 25, "void_magic": 20}', 20, 'Touches the void');

-- Shoes (20 items)
INSERT INTO public.equipment (name, category, tier, stat_modifiers, unlock_level, description) VALUES
('Traveler''s Boots', 'shoes', 1, '{"speed": 5}', 1, 'Comfortable walking boots'),
('Iron Greaves', 'shoes', 1, '{"defense": 5}', 3, 'Heavy metal boots'),
('Sandwalkers', 'shoes', 2, '{"desert_movement": 10}', 6, 'Perfect for sand'),
('Froststep Boots', 'shoes', 2, '{"cold_resist": 10, "speed": 5}', 8, 'Walk on ice'),
('Shadowstep Shoes', 'shoes', 3, '{"stealth": 15, "speed": 10}', 11, 'Silent movement'),
('Bonewalker Boots', 'shoes', 2, '{"defense": 8}', 7, 'Bone-reinforced'),
('Mage''s Slippers', 'shoes', 2, '{"magic_power": 8}', 5, 'Enchanted footwear'),
('Stormstride Boots', 'shoes', 3, '{"lightning_resist": 15, "speed": 12}', 13, 'Move like lightning'),
('Firestride Sandals', 'shoes', 3, '{"fire_resist": 15, "speed": 10}', 12, 'Walk through flames'),
('Winged Greaves', 'shoes', 4, '{"speed": 20, "evasion": 10}', 16, 'Nearly fly'),
('Serpent Coil Boots', 'shoes', 2, '{"poison_resist": 10, "agility": 8}', 9, 'Serpent-scaled'),
('Steelclad Boots', 'shoes', 2, '{"defense": 12}', 8, 'Heavy protection'),
('Crystal Steps', 'shoes', 3, '{"magic_power": 12, "speed": 8}', 12, 'Crystal-soled'),
('Bloodwalker Shoes', 'shoes', 3, '{"life_steal": 10}', 14, 'Drain life with steps'),
('Ghoststride Slippers', 'shoes', 4, '{"evasion": 20, "speed": 15}', 17, 'Phase through attacks'),
('Thornstep Boots', 'shoes', 3, '{"damage": 10, "defense": 10}', 13, 'Thorned soles'),
('Ironhoof Greaves', 'shoes', 3, '{"strength": 12, "defense": 10}', 14, 'Like iron hooves'),
('Moonveil Boots', 'shoes', 4, '{"stealth': 18, "magic_power": 10}', 18, 'Blessed by moon'),
('Swamp Treader Boots', 'shoes', 2, '{"poison_resist": 12, "swamp_movement": 10}', 10, 'Navigate swamps'),
('Ashen Marchers', 'shoes', 4, '{"fire_resist": 20, "speed": 15}', 19, 'March through ash');

-- Accessories (20 items)
INSERT INTO public.equipment (name, category, tier, stat_modifiers, unlock_level, description) VALUES
('Copper Ring', 'accessories', 1, '{"luck": 3}', 1, 'Simple copper band'),
('Amulet of Minor Protection', 'accessories', 1, '{"defense": 5}', 2, 'Basic protective charm'),
('Band of Focus', 'accessories', 2, '{"magic_power": 8}', 5, 'Improves concentration'),
('Pendant of Shadows', 'accessories', 2, '{"dark_magic": 10}', 7, 'Dark energy pendant'),
('Charm of Frost', 'accessories', 2, '{"ice_magic": 10}', 6, 'Icy charm'),
('Ring of Embers', 'accessories', 2, '{"fire_magic": 10}', 6, 'Warm to touch'),
('Chain of Whispers', 'accessories', 3, '{"perception": 15}', 11, 'Hear distant sounds'),
('Amulet of the Drowned', 'accessories', 3, '{"water_magic": 15}', 12, 'From sunken city'),
('Sandstone Talisman', 'accessories', 2, '{"earth_magic": 10}', 8, 'Desert artifact'),
('Serpent''s Fang Pendant', 'accessories', 3, '{"poison_damage": 15}', 10, 'Actual serpent fang'),
('Ring of Storms', 'accessories', 3, '{"lightning_magic": 15}', 13, 'Crackles with energy'),
('Crystal Pendant', 'accessories', 3, '{"all_magic": 12}', 12, 'Pure mana crystal'),
('Ring of the Forgotten', 'accessories', 4, '{"dark_magic": 20}', 15, 'Cursed ring'),
('Silver Ankh', 'accessories', 4, '{"light_magic": 20}', 16, 'Holy symbol'),
('Bracelet of Wyrms', 'accessories', 4, '{"dragon_affinity": 18}', 17, 'Dragon-blessed'),
('Bonecarved Necklace', 'accessories', 3, '{"dark_magic": 12, "defense": 8}', 14, 'Carved from ancient bones'),
('Bloodstone Ring', 'accessories', 4, '{"life_steal": 15}', 18, 'Drains life force'),
('Gilded Bracelet', 'accessories', 3, '{"luck": 15, "charisma": 10}', 13, 'Golden and ornate'),
('Charm of the Wilds', 'accessories', 3, '{"nature_affinity": 15}', 11, 'Connects to nature'),
('Voidstone Amulet', 'accessories', 5, '{"void_magic": 25}', 20, 'Contains void essence');
